"""add process types

Revision ID: 4764e22ac247
Revises: 809993bc44d2
Create Date: 2026-06-08 18:12:15.978928

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4764e22ac247'
down_revision = '809993bc44d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_types_name'), 'process_types', ['name'], unique=True)
    op.add_column('experiments', sa.Column('process_type_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_experiments_process_type_id'), 'experiments', ['process_type_id'], unique=False)
    op.create_foreign_key(None, 'experiments', 'process_types', ['process_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'experiments', type_='foreignkey')
    op.drop_index(op.f('ix_experiments_process_type_id'), table_name='experiments')
    op.drop_column('experiments', 'process_type_id')
    op.drop_index(op.f('ix_process_types_name'), table_name='process_types')
    op.drop_table('process_types')
    # ### end Alembic commands ###

