"""add record process type override

Revision ID: 7b33152bcbdb
Revises: 4764e22ac247
Create Date: 2026-06-08 18:13:09.912957

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b33152bcbdb'
down_revision = '4764e22ac247'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('process_type_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_records_process_type_id'), 'records', ['process_type_id'], unique=False)
    op.create_foreign_key(None, 'records', 'process_types', ['process_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'records', type_='foreignkey')
    op.drop_index(op.f('ix_records_process_type_id'), table_name='records')
    op.drop_column('records', 'process_type_id')
    # ### end Alembic commands ###

