"""drop material_key

Revision ID: 809993bc44d2
Revises: e14788f3cad6
Create Date: 2026-06-08 18:07:24.815059

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '809993bc44d2'
down_revision = 'e14788f3cad6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_materials_material_key'), table_name='materials')
    op.drop_column('materials', 'material_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('material_key', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_materials_material_key'), 'materials', ['material_key'], unique=True)
    # ### end Alembic commands ###

