"""curing_agent default_ratio status drop is_active

Revision ID: 863e9dfc7b1b
Revises: 8cf38ceba49f
Create Date: 2026-06-08 20:09:14.626591

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '863e9dfc7b1b'
down_revision = '8cf38ceba49f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curing_agents', sa.Column('default_ratio', sa.Float(), nullable=True))
    op.add_column('curing_agents', sa.Column('status', sa.String(length=128), nullable=True))
    op.drop_column('curing_agents', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curing_agents', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_column('curing_agents', 'status')
    op.drop_column('curing_agents', 'default_ratio')
    # ### end Alembic commands ###

