"""add audit_events

Revision ID: 89bd25c39b26
Revises: 9a1a7b2c3d4e
Create Date: 2026-06-11 11:14:03.021580

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '89bd25c39b26'
down_revision = '9a1a7b2c3d4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('actor_name', sa.String(length=128), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('diff', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_events_action_ts', 'audit_events', ['action', 'ts'], unique=False)
    op.create_index('ix_audit_events_actor_id_ts', 'audit_events', ['actor_id', 'ts'], unique=False)
    op.create_index('ix_audit_events_entity_ts', 'audit_events', ['entity_type', 'entity_id', 'ts'], unique=False)
    op.create_index('ix_audit_events_ts', 'audit_events', ['ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_events_ts', table_name='audit_events')
    op.drop_index('ix_audit_events_entity_ts', table_name='audit_events')
    op.drop_index('ix_audit_events_actor_id_ts', table_name='audit_events')
    op.drop_index('ix_audit_events_action_ts', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###

