"""add material numeric fields

Revision ID: 8cf38ceba49f
Revises: feac083de0ce
Create Date: 2026-06-08 19:37:34.687624

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cf38ceba49f'
down_revision = 'feac083de0ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('hydrogen_content', sa.Float(), nullable=True))
    op.add_column('materials', sa.Column('volatile_min', sa.Float(), nullable=True))
    op.add_column('materials', sa.Column('volatile_max', sa.Float(), nullable=True))
    op.add_column('materials', sa.Column('avg_mw_wan', sa.Float(), nullable=True))
    op.add_column('materials', sa.Column('pt_ppm', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materials', 'pt_ppm')
    op.drop_column('materials', 'avg_mw_wan')
    op.drop_column('materials', 'volatile_max')
    op.drop_column('materials', 'volatile_min')
    op.drop_column('materials', 'hydrogen_content')
    # ### end Alembic commands ###

