"""init tables

Revision ID: b731abf80eb4
Revises: 
Create Date: 2026-06-08 17:50:49.564868

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b731abf80eb4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curing_agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curing_agents_name'), 'curing_agents', ['name'], unique=True)
    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=128), nullable=False),
    sa.Column('project_no', sa.String(length=64), nullable=False),
    sa.Column('debug_goal', sa.Text(), nullable=False),
    sa.Column('silicone_model', sa.String(length=128), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cure_temp_c', sa.Float(), nullable=True),
    sa.Column('cure_time_min', sa.Float(), nullable=True),
    sa.Column('bake_temp_c', sa.Float(), nullable=True),
    sa.Column('bake_time_min', sa.Float(), nullable=True),
    sa.Column('sheet_thickness_mm', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiments_customer_name'), 'experiments', ['customer_name'], unique=False)
    op.create_index(op.f('ix_experiments_project_no'), 'experiments', ['project_no'], unique=False)
    op.create_index(op.f('ix_experiments_silicone_model'), 'experiments', ['silicone_model'], unique=False)
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('curing_agent_a_id', sa.Integer(), nullable=False),
    sa.Column('curing_agent_b_id', sa.Integer(), nullable=False),
    sa.Column('ratio_a_pct', sa.Float(), nullable=False),
    sa.Column('ratio_b_pct', sa.Float(), nullable=False),
    sa.Column('ml', sa.Float(), nullable=False),
    sa.Column('mh', sa.Float(), nullable=False),
    sa.Column('t10_sec', sa.Integer(), nullable=False),
    sa.Column('t90_sec', sa.Integer(), nullable=False),
    sa.Column('bubble_grade', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('cure_temp_c', sa.Float(), nullable=True),
    sa.Column('cure_time_min', sa.Float(), nullable=True),
    sa.Column('bake_temp_c', sa.Float(), nullable=True),
    sa.Column('bake_time_min', sa.Float(), nullable=True),
    sa.Column('sheet_thickness_mm', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(ratio_a_pct + ratio_b_pct) < 100', name='ck_ratio_sum_lt_100'),
    sa.CheckConstraint('bubble_grade >= 0 AND bubble_grade <= 5', name='ck_bubble_grade_0_5'),
    sa.CheckConstraint('ratio_a_pct >= 0 AND ratio_a_pct <= 100', name='ck_ratio_a_pct'),
    sa.CheckConstraint('ratio_b_pct >= 0 AND ratio_b_pct <= 100', name='ck_ratio_b_pct'),
    sa.ForeignKeyConstraint(['curing_agent_a_id'], ['curing_agents.id'], ),
    sa.ForeignKeyConstraint(['curing_agent_b_id'], ['curing_agents.id'], ),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_records_curing_agent_a_id'), 'records', ['curing_agent_a_id'], unique=False)
    op.create_index(op.f('ix_records_curing_agent_b_id'), 'records', ['curing_agent_b_id'], unique=False)
    op.create_index(op.f('ix_records_experiment_id'), 'records', ['experiment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_records_experiment_id'), table_name='records')
    op.drop_index(op.f('ix_records_curing_agent_b_id'), table_name='records')
    op.drop_index(op.f('ix_records_curing_agent_a_id'), table_name='records')
    op.drop_table('records')
    op.drop_index(op.f('ix_experiments_silicone_model'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_project_no'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_customer_name'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_curing_agents_name'), table_name='curing_agents')
    op.drop_table('curing_agents')
    # ### end Alembic commands ###

