"""materials unique category+name

Revision ID: c9fe6c7fa3b4
Revises: 7b33152bcbdb
Create Date: 2026-06-08 18:16:47.200722

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9fe6c7fa3b4'
down_revision = '7b33152bcbdb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_materials_category_name', 'materials', ['category', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_materials_category_name', 'materials', type_='unique')
    # ### end Alembic commands ###

