"""add materials and curing_agent composition

Revision ID: e14788f3cad6
Revises: b731abf80eb4
Create Date: 2026-06-08 18:05:48.416323

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'e14788f3cad6'
down_revision = 'b731abf80eb4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('vinyl_content', sa.Float(), nullable=True),
    sa.Column('material_key', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_category'), 'materials', ['category'], unique=False)
    op.create_index(op.f('ix_materials_material_key'), 'materials', ['material_key'], unique=True)
    op.create_index(op.f('ix_materials_name'), 'materials', ['name'], unique=False)
    op.add_column('curing_agents', sa.Column('composition', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('curing_agents', 'composition')
    op.drop_index(op.f('ix_materials_name'), table_name='materials')
    op.drop_index(op.f('ix_materials_material_key'), table_name='materials')
    op.drop_index(op.f('ix_materials_category'), table_name='materials')
    op.drop_table('materials')
    # ### end Alembic commands ###

