set check_function_bodies = off;

create extension if not exists pgcrypto with schema extensions;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique,
  display_name text not null,
  role text not null default 'viewer' check (role in ('admin', 'auditor', 'editor', 'viewer')),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.process_types (
  id integer generated by default as identity primary key,
  name varchar(32) not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.materials (
  id integer generated by default as identity primary key,
  category varchar(32) not null,
  name varchar(64) not null,
  hydrogen_content double precision,
  vinyl_content double precision,
  volatile_min double precision,
  volatile_max double precision,
  avg_mw_wan double precision,
  pt_ppm double precision,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_materials_category_name unique (category, name)
);

create table public.curing_agents (
  id integer generated by default as identity primary key,
  name varchar(64) not null unique,
  default_ratio double precision,
  status varchar(128),
  note text,
  composition jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.experiments (
  id integer generated by default as identity primary key,
  customer_name varchar(128) not null,
  project_no varchar(64) not null,
  status varchar(32) not null default '待开始' check (status in ('待开始', '进行中', '已结束')),
  debug_goal text,
  silicone_model varchar(128) not null,
  process_type_id integer not null references public.process_types(id),
  final_record_id integer,
  start_at timestamptz not null,
  end_at timestamptz,
  cure_temp_c double precision,
  cure_time_min double precision,
  bake_temp_c double precision,
  bake_time_min double precision,
  sheet_thickness_mm double precision,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.records (
  id integer generated by default as identity primary key,
  experiment_id integer not null references public.experiments(id) on delete cascade,
  process_type_id integer references public.process_types(id),
  curing_agent_a_id integer not null references public.curing_agents(id),
  curing_agent_b_id integer not null references public.curing_agents(id),
  ratio_a_pct double precision not null,
  ratio_b_pct double precision not null,
  ml double precision not null,
  mh double precision not null,
  t10_sec integer not null,
  t90_sec integer not null,
  bubble_grade integer not null,
  note text,
  cure_temp_c double precision,
  cure_time_min double precision,
  bake_temp_c double precision,
  bake_time_min double precision,
  sheet_thickness_mm double precision,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ck_ratio_a_pct check (ratio_a_pct >= 0 and ratio_a_pct <= 100),
  constraint ck_ratio_b_pct check (ratio_b_pct >= 0 and ratio_b_pct <= 100),
  constraint ck_ratio_sum_lt_100 check ((ratio_a_pct + ratio_b_pct) < 100),
  constraint ck_bubble_grade_0_5 check (bubble_grade >= 0 and bubble_grade <= 5)
);

alter table public.experiments
  add constraint experiments_final_record_id_fkey
  foreign key (final_record_id) references public.records(id) on delete set null;

create table public.audit_events (
  id integer generated by default as identity primary key,
  ts timestamptz not null default now(),
  actor_type varchar(16) not null,
  actor_id varchar(64),
  actor_name varchar(128),
  action varchar(64) not null,
  entity_type varchar(64) not null,
  entity_id varchar(64) not null,
  request_id varchar(64),
  ip varchar(64),
  user_agent text,
  "before" jsonb,
  "after" jsonb,
  diff jsonb,
  reason text
);

create index ix_materials_category on public.materials(category);
create index ix_materials_name on public.materials(name);
create index ix_curing_agents_name on public.curing_agents(name);
create index ix_experiments_customer_name on public.experiments(customer_name);
create index ix_experiments_project_no on public.experiments(project_no);
create index ix_experiments_silicone_model on public.experiments(silicone_model);
create index ix_experiments_status on public.experiments(status);
create index ix_experiments_process_type_id on public.experiments(process_type_id);
create index ix_experiments_final_record_id on public.experiments(final_record_id);
create index ix_records_experiment_id on public.records(experiment_id);
create index ix_records_process_type_id on public.records(process_type_id);
create index ix_records_curing_agent_a_id on public.records(curing_agent_a_id);
create index ix_records_curing_agent_b_id on public.records(curing_agent_b_id);
create index ix_audit_events_ts on public.audit_events(ts);
create index ix_audit_events_actor_id_ts on public.audit_events(actor_id, ts);
create index ix_audit_events_entity_ts on public.audit_events(entity_type, entity_id, ts);
create index ix_audit_events_action_ts on public.audit_events(action, ts);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_touch_updated_at
before update on public.profiles
for each row execute function public.touch_updated_at();

create trigger process_types_touch_updated_at
before update on public.process_types
for each row execute function public.touch_updated_at();

create trigger materials_touch_updated_at
before update on public.materials
for each row execute function public.touch_updated_at();

create trigger curing_agents_touch_updated_at
before update on public.curing_agents
for each row execute function public.touch_updated_at();

create trigger experiments_touch_updated_at
before update on public.experiments
for each row execute function public.touch_updated_at();

create trigger records_touch_updated_at
before update on public.records
for each row execute function public.touch_updated_at();

create or replace function public.current_user_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select p.role
  from public.profiles p
  where p.id = auth.uid()
    and p.is_active is true
  limit 1
$$;

create or replace function public.has_app_role(allowed_roles text[])
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.current_user_role() = any(allowed_roles), false)
$$;

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, display_name, role)
  values (
    new.id,
    new.email,
    coalesce(nullif(new.raw_user_meta_data ->> 'display_name', ''), split_part(coalesce(new.email, ''), '@', 1), '用户'),
    'viewer'
  )
  on conflict (id) do update
  set email = excluded.email,
      updated_at = now();
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_auth_user();

create or replace function public.normalize_experiment_status()
returns trigger
language plpgsql
as $$
begin
  if new.status is null then
    new.status = '待开始';
  end if;

  if new.status = '已结束' then
    if new.end_at is null or new.end_at = new.start_at then
      new.end_at = now();
    end if;
  else
    new.end_at = null;
  end if;

  return new;
end;
$$;

create trigger experiments_normalize_status
before insert or update of status, start_at, end_at on public.experiments
for each row execute function public.normalize_experiment_status();

create or replace function public.validate_experiment_final_record()
returns trigger
language plpgsql
as $$
declare
  record_experiment_id integer;
begin
  if new.final_record_id is null then
    return new;
  end if;

  select r.experiment_id
  into record_experiment_id
  from public.records r
  where r.id = new.final_record_id;

  if record_experiment_id is null then
    raise exception 'final_record_id not found' using errcode = '23503';
  end if;

  if record_experiment_id <> new.id then
    raise exception 'final_record_id must belong to the experiment' using errcode = '23514';
  end if;

  return new;
end;
$$;

create trigger experiments_validate_final_record
before insert or update of final_record_id on public.experiments
for each row execute function public.validate_experiment_final_record();

create or replace function public.validate_curing_agent_composition()
returns trigger
language plpgsql
as $$
declare
  item jsonb;
  material_id integer;
  mass_pct double precision;
  total double precision := 0;
  material_ids integer[] := '{}';
begin
  if new.composition is null then
    return new;
  end if;

  if jsonb_typeof(new.composition) <> 'array' then
    raise exception 'composition must be an array' using errcode = '23514';
  end if;

  if jsonb_array_length(new.composition) = 0 then
    new.composition = null;
    return new;
  end if;

  for item in select value from jsonb_array_elements(new.composition)
  loop
    material_id := nullif(item ->> 'material_id', '')::integer;
    mass_pct := nullif(item ->> 'mass_pct', '')::double precision;

    if material_id is null or mass_pct is null then
      raise exception 'composition rows require material_id and mass_pct' using errcode = '23514';
    end if;

    if mass_pct < 0 or mass_pct > 100 then
      raise exception 'composition mass_pct must be between 0 and 100' using errcode = '23514';
    end if;

    if material_id = any(material_ids) then
      raise exception 'composition material_id duplicated' using errcode = '23514';
    end if;

    if not exists (select 1 from public.materials m where m.id = material_id) then
      raise exception 'composition material_id not found: %', material_id using errcode = '23503';
    end if;

    material_ids := array_append(material_ids, material_id);
    total := total + mass_pct;
  end loop;

  if abs(total - 100) > 0.000001 then
    raise exception 'composition mass_pct must sum to 100' using errcode = '23514';
  end if;

  return new;
end;
$$;

create trigger curing_agents_validate_composition
before insert or update of composition on public.curing_agents
for each row execute function public.validate_curing_agent_composition();

create or replace function public.auto_start_experiment_on_record()
returns trigger
language plpgsql
as $$
begin
  perform set_config('app.suppress_audit', 'on', true);
  update public.experiments
  set status = '进行中'
  where id = new.experiment_id
    and status = '待开始';
  perform set_config('app.suppress_audit', 'off', true);
  return new;
end;
$$;

create trigger records_auto_start_experiment
after insert on public.records
for each row execute function public.auto_start_experiment_on_record();

create or replace function public.request_header(header_name text)
returns text
language plpgsql
stable
as $$
declare
  headers jsonb;
begin
  headers := nullif(current_setting('request.headers', true), '')::jsonb;
  return headers ->> lower(header_name);
exception
  when others then
    return null;
end;
$$;

create or replace function public.jsonb_diff(before_row jsonb, after_row jsonb)
returns jsonb
language sql
immutable
as $$
  select coalesce(
    jsonb_object_agg(key, jsonb_build_object('from', old_value, 'to', new_value)),
    '{}'::jsonb
  )
  from (
    select coalesce(n.key, o.key) as key, o.value as old_value, n.value as new_value
    from jsonb_each(coalesce(after_row, '{}'::jsonb)) n
    full join jsonb_each(coalesce(before_row, '{}'::jsonb)) o using (key)
    where n.value is distinct from o.value
  ) d
$$;

create or replace function public.audit_business_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  before_row jsonb;
  after_row jsonb;
  action_name text;
  actor_display_name text;
  actor_uuid uuid;
  entity_id_text text;
begin
  if current_setting('app.suppress_audit', true) = 'on' then
    if tg_op = 'DELETE' then
      return old;
    end if;
    return new;
  end if;

  actor_uuid := auth.uid();
  select p.display_name
  into actor_display_name
  from public.profiles p
  where p.id = actor_uuid;

  if tg_op = 'INSERT' then
    after_row := to_jsonb(new);
    action_name := tg_table_name || '.create';
    entity_id_text := new.id::text;
  elsif tg_op = 'UPDATE' then
    before_row := to_jsonb(old);
    after_row := to_jsonb(new);
    action_name := tg_table_name || '.update';
    entity_id_text := new.id::text;
  else
    before_row := to_jsonb(old);
    action_name := tg_table_name || '.delete';
    entity_id_text := old.id::text;
  end if;

  action_name := replace(action_name, 'experiments.', 'experiment.');
  action_name := replace(action_name, 'records.', 'record.');
  action_name := replace(action_name, 'materials.', 'material.');
  action_name := replace(action_name, 'curing_agents.', 'curing_agent.');

  insert into public.audit_events (
    actor_type,
    actor_id,
    actor_name,
    action,
    entity_type,
    entity_id,
    request_id,
    ip,
    user_agent,
    "before",
    "after",
    diff
  )
  values (
    'user',
    actor_uuid::text,
    actor_display_name,
    action_name,
    case tg_table_name
      when 'curing_agents' then 'curing_agent'
      else regexp_replace(tg_table_name, 's$', '')
    end,
    entity_id_text,
    public.request_header('x-request-id'),
    public.request_header('x-forwarded-for'),
    public.request_header('user-agent'),
    before_row,
    after_row,
    case when tg_op = 'UPDATE' then public.jsonb_diff(before_row, after_row) else null end
  );

  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

create trigger materials_audit
after insert or update or delete on public.materials
for each row execute function public.audit_business_change();

create trigger curing_agents_audit
after insert or update or delete on public.curing_agents
for each row execute function public.audit_business_change();

create trigger experiments_audit
after insert or update or delete on public.experiments
for each row execute function public.audit_business_change();

create trigger records_audit
after insert or update or delete on public.records
for each row execute function public.audit_business_change();

alter table public.profiles enable row level security;
alter table public.process_types enable row level security;
alter table public.materials enable row level security;
alter table public.curing_agents enable row level security;
alter table public.experiments enable row level security;
alter table public.records enable row level security;
alter table public.audit_events enable row level security;

create policy "profiles read own or admin"
on public.profiles for select to authenticated
using (id = auth.uid() or public.has_app_role(array['admin']));

create policy "profiles update admin"
on public.profiles for update to authenticated
using (public.has_app_role(array['admin']))
with check (public.has_app_role(array['admin']));

create policy "process_types read authenticated"
on public.process_types for select to authenticated
using (public.has_app_role(array['admin', 'auditor', 'editor', 'viewer']));

create policy "process_types write admin"
on public.process_types for all to authenticated
using (public.has_app_role(array['admin']))
with check (public.has_app_role(array['admin']));

create policy "materials read authenticated"
on public.materials for select to authenticated
using (public.has_app_role(array['admin', 'auditor', 'editor', 'viewer']));

create policy "materials insert editors"
on public.materials for insert to authenticated
with check (public.has_app_role(array['admin', 'editor']));

create policy "materials update editors"
on public.materials for update to authenticated
using (public.has_app_role(array['admin', 'editor']))
with check (public.has_app_role(array['admin', 'editor']));

create policy "materials delete editors"
on public.materials for delete to authenticated
using (public.has_app_role(array['admin', 'editor']));

create policy "curing_agents read authenticated"
on public.curing_agents for select to authenticated
using (public.has_app_role(array['admin', 'auditor', 'editor', 'viewer']));

create policy "curing_agents insert editors"
on public.curing_agents for insert to authenticated
with check (public.has_app_role(array['admin', 'editor']));

create policy "curing_agents update editors"
on public.curing_agents for update to authenticated
using (public.has_app_role(array['admin', 'editor']))
with check (public.has_app_role(array['admin', 'editor']));

create policy "curing_agents delete editors"
on public.curing_agents for delete to authenticated
using (public.has_app_role(array['admin', 'editor']));

create policy "experiments read authenticated"
on public.experiments for select to authenticated
using (public.has_app_role(array['admin', 'auditor', 'editor', 'viewer']));

create policy "experiments insert editors"
on public.experiments for insert to authenticated
with check (public.has_app_role(array['admin', 'editor']));

create policy "experiments update editors"
on public.experiments for update to authenticated
using (public.has_app_role(array['admin', 'editor']))
with check (public.has_app_role(array['admin', 'editor']));

create policy "experiments delete editors"
on public.experiments for delete to authenticated
using (public.has_app_role(array['admin', 'editor']));

create policy "records read authenticated"
on public.records for select to authenticated
using (public.has_app_role(array['admin', 'auditor', 'editor', 'viewer']));

create policy "records insert editors"
on public.records for insert to authenticated
with check (public.has_app_role(array['admin', 'editor']));

create policy "records update editors"
on public.records for update to authenticated
using (public.has_app_role(array['admin', 'editor']))
with check (public.has_app_role(array['admin', 'editor']));

create policy "records delete editors"
on public.records for delete to authenticated
using (public.has_app_role(array['admin', 'editor']));

create policy "audit_events read auditors"
on public.audit_events for select to authenticated
using (public.has_app_role(array['admin', 'auditor']));

insert into public.process_types (name)
values ('挤出'), ('压延'), ('模压')
on conflict (name) do nothing;

create or replace function public.list_experiments(
  p_process_type_id integer default null,
  p_status text default null,
  p_curing_agent_id integer default null,
  p_q text default null,
  p_limit integer default 50,
  p_offset integer default 0
)
returns setof public.experiments
language sql
stable
security invoker
set search_path = public
as $$
  select e.*
  from public.experiments e
  where (p_process_type_id is null or e.process_type_id = p_process_type_id)
    and (p_status is null or e.status = p_status)
    and (
      p_curing_agent_id is null
      or exists (
        select 1
        from public.records r
        where r.experiment_id = e.id
          and (r.curing_agent_a_id = p_curing_agent_id or r.curing_agent_b_id = p_curing_agent_id)
      )
    )
    and (
      nullif(trim(coalesce(p_q, '')), '') is null
      or e.customer_name ilike '%' || trim(p_q) || '%'
      or e.project_no ilike '%' || trim(p_q) || '%'
      or e.silicone_model ilike '%' || trim(p_q) || '%'
    )
  order by e.id desc
  limit least(greatest(coalesce(p_limit, 50), 1), 200)
  offset greatest(coalesce(p_offset, 0), 0)
$$;

create or replace function public.list_records(
  p_experiment_id integer default null,
  p_process_type_id integer default null,
  p_limit integer default 50,
  p_offset integer default 0
)
returns setof public.records
language sql
stable
security invoker
set search_path = public
as $$
  select r.*
  from public.records r
  join public.experiments e on e.id = r.experiment_id
  where (p_experiment_id is null or r.experiment_id = p_experiment_id)
    and (p_process_type_id is null or coalesce(r.process_type_id, e.process_type_id) = p_process_type_id)
  order by r.id desc
  limit least(greatest(coalesce(p_limit, 50), 1), 200)
  offset greatest(coalesce(p_offset, 0), 0)
$$;

create or replace function public.curing_agents_with_usage(
  p_limit integer default 50,
  p_offset integer default 0
)
returns table (
  id integer,
  name varchar(64),
  default_ratio double precision,
  status varchar(128),
  note text,
  composition jsonb,
  created_at timestamptz,
  updated_at timestamptz,
  used_record_count integer
)
language sql
stable
security invoker
set search_path = public
as $$
  select
    ca.id,
    ca.name,
    ca.default_ratio,
    ca.status,
    ca.note,
    ca.composition,
    ca.created_at,
    ca.updated_at,
    count(r.id)::integer as used_record_count
  from public.curing_agents ca
  left join public.records r
    on r.curing_agent_a_id = ca.id
    or r.curing_agent_b_id = ca.id
  group by ca.id
  order by ca.name
  limit least(greatest(coalesce(p_limit, 50), 1), 200)
  offset greatest(coalesce(p_offset, 0), 0)
$$;

create or replace function public.experiment_suggestions(p_limit integer default 200)
returns jsonb
language sql
stable
security invoker
set search_path = public
as $$
  with customers as (
    select customer_name as value, count(*) as n
    from public.experiments
    where customer_name is not null and length(trim(customer_name)) > 0
    group by customer_name
    order by count(*) desc, customer_name asc
    limit least(greatest(coalesce(p_limit, 200), 1), 500)
  ),
  models as (
    select silicone_model as value, count(*) as n
    from public.experiments
    where silicone_model is not null and length(trim(silicone_model)) > 0
    group by silicone_model
    order by count(*) desc, silicone_model asc
    limit least(greatest(coalesce(p_limit, 200), 1), 500)
  )
  select jsonb_build_object(
    'customers',
    coalesce((select jsonb_agg(value) from customers), '[]'::jsonb) || case when exists (select 1 from customers where value = '其它') then '[]'::jsonb else '["其它"]'::jsonb end,
    'silicone_models',
    coalesce((select jsonb_agg(value) from models), '[]'::jsonb) || case when exists (select 1 from models where value = '其它') then '[]'::jsonb else '["其它"]'::jsonb end
  )
$$;

create or replace function public.dashboard_stats(
  p_completed_days integer default 7,
  p_top_n integer default 5
)
returns jsonb
language plpgsql
stable
security invoker
set search_path = public
as $$
declare
  completed_since timestamptz := now() - make_interval(days => least(greatest(coalesce(p_completed_days, 7), 1), 3650));
  week_start timestamptz := date_trunc('week', now());
  top_n integer := least(greatest(coalesce(p_top_n, 5), 1), 20);
  a_total integer;
  b_total integer;
  a_top_sum integer;
  b_top_sum integer;
  a_top jsonb;
  b_top jsonb;
begin
  with a_rows as (
    select r.curing_agent_a_id as curing_agent_id, ca.name, count(*)::integer as count
    from public.records r
    join public.curing_agents ca on ca.id = r.curing_agent_a_id
    group by r.curing_agent_a_id, ca.name
    order by count(*) desc
    limit top_n
  ),
  b_rows as (
    select r.curing_agent_b_id as curing_agent_id, ca.name, count(*)::integer as count
    from public.records r
    join public.curing_agents ca on ca.id = r.curing_agent_b_id
    group by r.curing_agent_b_id, ca.name
    order by count(*) desc
    limit top_n
  )
  select
    coalesce((select jsonb_agg(to_jsonb(a_rows)) from a_rows), '[]'::jsonb),
    coalesce((select jsonb_agg(to_jsonb(b_rows)) from b_rows), '[]'::jsonb),
    coalesce((select sum(count)::integer from a_rows), 0),
    coalesce((select sum(count)::integer from b_rows), 0)
  into a_top, b_top, a_top_sum, b_top_sum;

  select count(*)::integer into a_total from public.records;
  select count(*)::integer into b_total from public.records;

  return jsonb_build_object(
    'curing_agents_a_top', a_top,
    'curing_agents_a_other_count', greatest(0, a_total - a_top_sum),
    'curing_agents_b_top', b_top,
    'curing_agents_b_other_count', greatest(0, b_total - b_top_sum),
    'ongoing_experiments_count', (select count(*)::integer from public.experiments where status = '进行中'),
    'completed_experiments_count', (select count(*)::integer from public.experiments where status = '已结束' and end_at >= completed_since),
    'new_experiments_this_week_count', (select count(*)::integer from public.experiments where created_at >= week_start)
  );
end;
$$;

create or replace function public.delete_experiment(p_experiment_id integer)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  before_row jsonb;
  actor_uuid uuid;
  actor_display_name text;
begin
  if not public.has_app_role(array['admin', 'editor']) then
    raise exception 'Forbidden' using errcode = '42501';
  end if;

  select to_jsonb(e)
  into before_row
  from public.experiments e
  where e.id = p_experiment_id;

  if before_row is null then
    raise exception 'Experiment not found' using errcode = 'P0002';
  end if;

  actor_uuid := auth.uid();
  select p.display_name
  into actor_display_name
  from public.profiles p
  where p.id = actor_uuid;

  perform set_config('app.suppress_audit', 'on', true);
  update public.experiments
  set final_record_id = null
  where id = p_experiment_id;

  delete from public.experiments
  where id = p_experiment_id;
  perform set_config('app.suppress_audit', 'off', true);

  insert into public.audit_events (
    actor_type,
    actor_id,
    actor_name,
    action,
    entity_type,
    entity_id,
    request_id,
    ip,
    user_agent,
    "before"
  )
  values (
    'user',
    actor_uuid::text,
    actor_display_name,
    'experiment.delete',
    'experiment',
    p_experiment_id::text,
    public.request_header('x-request-id'),
    public.request_header('x-forwarded-for'),
    public.request_header('user-agent'),
    before_row
  );
end;
$$;

create or replace function public.export_records_rows(
  p_experiment_id integer default null,
  p_process_type_id integer default null,
  p_status text default null,
  p_curing_agent_id integer default null,
  p_customer_q text default null,
  p_silicone_model_q text default null,
  p_project_no_q text default null,
  p_start_from timestamptz default null,
  p_start_to timestamptz default null,
  p_only_final boolean default false,
  p_limit integer default 20000
)
returns table (
  record_id integer,
  experiment_id integer,
  effective_process_type_id integer,
  process_type_name text,
  is_final boolean,
  curing_agent_a_id integer,
  curing_agent_a_name text,
  ratio_a_pct double precision,
  curing_agent_b_id integer,
  curing_agent_b_name text,
  ratio_b_pct double precision,
  ml double precision,
  mh double precision,
  t10_sec integer,
  t90_sec integer,
  bubble_grade integer,
  record_note text,
  record_created_at timestamptz,
  record_updated_at timestamptz,
  customer_name text,
  project_no text,
  silicone_model text,
  debug_goal text,
  experiment_start_at timestamptz,
  experiment_end_at timestamptz,
  experiment_note text,
  experiment_created_at timestamptz,
  experiment_updated_at timestamptz
)
language sql
stable
security invoker
set search_path = public
as $$
  select
    r.id,
    r.experiment_id,
    coalesce(r.process_type_id, e.process_type_id),
    pt.name::text,
    e.final_record_id = r.id,
    r.curing_agent_a_id,
    ca.name::text,
    r.ratio_a_pct,
    r.curing_agent_b_id,
    cb.name::text,
    r.ratio_b_pct,
    r.ml,
    r.mh,
    r.t10_sec,
    r.t90_sec,
    r.bubble_grade,
    r.note,
    r.created_at,
    r.updated_at,
    e.customer_name::text,
    e.project_no::text,
    e.silicone_model::text,
    e.debug_goal,
    e.start_at,
    e.end_at,
    e.note,
    e.created_at,
    e.updated_at
  from public.records r
  join public.experiments e on e.id = r.experiment_id
  left join public.process_types pt on pt.id = coalesce(r.process_type_id, e.process_type_id)
  join public.curing_agents ca on ca.id = r.curing_agent_a_id
  join public.curing_agents cb on cb.id = r.curing_agent_b_id
  where (p_experiment_id is null or r.experiment_id = p_experiment_id)
    and (p_process_type_id is null or coalesce(r.process_type_id, e.process_type_id) = p_process_type_id)
    and (p_status is null or e.status = p_status)
    and (p_curing_agent_id is null or r.curing_agent_a_id = p_curing_agent_id or r.curing_agent_b_id = p_curing_agent_id)
    and (nullif(trim(coalesce(p_customer_q, '')), '') is null or e.customer_name ilike '%' || trim(p_customer_q) || '%')
    and (nullif(trim(coalesce(p_silicone_model_q, '')), '') is null or e.silicone_model ilike '%' || trim(p_silicone_model_q) || '%')
    and (nullif(trim(coalesce(p_project_no_q, '')), '') is null or e.project_no ilike '%' || trim(p_project_no_q) || '%')
    and (p_start_from is null or e.start_at >= p_start_from)
    and (p_start_to is null or e.start_at <= p_start_to)
    and (p_only_final is false or e.final_record_id = r.id)
  order by r.id desc
  limit least(greatest(coalesce(p_limit, 20000), 1), 20000)
$$;

create or replace function public.export_experiments_rows(
  p_process_type_id integer default null,
  p_status text default null,
  p_curing_agent_id integer default null,
  p_customer_q text default null,
  p_silicone_model_q text default null,
  p_project_no_q text default null,
  p_start_from timestamptz default null,
  p_start_to timestamptz default null
)
returns table (
  experiment_id integer,
  customer_name text,
  project_no text,
  silicone_model text,
  debug_goal text,
  process_type_id integer,
  process_type_name text,
  start_at timestamptz,
  end_at timestamptz,
  note text,
  created_at timestamptz,
  updated_at timestamptz
)
language sql
stable
security invoker
set search_path = public
as $$
  select
    e.id,
    e.customer_name::text,
    e.project_no::text,
    e.silicone_model::text,
    e.debug_goal,
    e.process_type_id,
    pt.name::text,
    e.start_at,
    e.end_at,
    e.note,
    e.created_at,
    e.updated_at
  from public.experiments e
  left join public.process_types pt on pt.id = e.process_type_id
  where (p_process_type_id is null or e.process_type_id = p_process_type_id)
    and (p_status is null or e.status = p_status)
    and (
      p_curing_agent_id is null
      or exists (
        select 1
        from public.records r
        where r.experiment_id = e.id
          and (r.curing_agent_a_id = p_curing_agent_id or r.curing_agent_b_id = p_curing_agent_id)
      )
    )
    and (nullif(trim(coalesce(p_customer_q, '')), '') is null or e.customer_name ilike '%' || trim(p_customer_q) || '%')
    and (nullif(trim(coalesce(p_silicone_model_q, '')), '') is null or e.silicone_model ilike '%' || trim(p_silicone_model_q) || '%')
    and (nullif(trim(coalesce(p_project_no_q, '')), '') is null or e.project_no ilike '%' || trim(p_project_no_q) || '%')
    and (p_start_from is null or e.start_at >= p_start_from)
    and (p_start_to is null or e.start_at <= p_start_to)
  order by e.id desc
$$;

grant usage on schema public to authenticated;
grant select, insert, update, delete on all tables in schema public to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant execute on function public.current_user_role() to authenticated;
grant execute on function public.has_app_role(text[]) to authenticated;
grant execute on function public.list_experiments(integer, text, integer, text, integer, integer) to authenticated;
grant execute on function public.list_records(integer, integer, integer, integer) to authenticated;
grant execute on function public.curing_agents_with_usage(integer, integer) to authenticated;
grant execute on function public.experiment_suggestions(integer) to authenticated;
grant execute on function public.dashboard_stats(integer, integer) to authenticated;
grant execute on function public.delete_experiment(integer) to authenticated;
grant execute on function public.export_records_rows(integer, integer, text, integer, text, text, text, timestamptz, timestamptz, boolean, integer) to authenticated;
grant execute on function public.export_experiments_rows(integer, text, integer, text, text, text, timestamptz, timestamptz) to authenticated;
